// FILE AUTOGENERATED BY @zoopoetics/myna
// This is for the benefit of Jest. Individual packages should
// each have their own babel.config.js, and not inherit from this.
module.exports = require("@10x/myna/config/jest/babel.config.js");
